# ============================================
#         ЛОКАЛЬНАЯ РАЗРАБОТКА
# ============================================

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_db
spring.datasource.username=logistics_user
spring.datasource.password=logistics_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# === ДИСПЕТЧЕРИЗАЦИЯ ===
dispatch.system.url=http://host.docker.internal:8081
dispatch.system.username=admin
dispatch.system.password=admin123

sync.send.interval=60000
sync.send.enabled=true
sync.receive.interval=60000
sync.receive.enabled=true

logging.level.org.example=DEBUG
